kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: test
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "kv/data/test"
spec:
  host: test.apps.didak6.tbtk.gov.tr
  path: /
  to:
    kind: Service
    name: argocd-sample-server
    weight: 100
  port:
    targetPort: 8083
  tls:
    termination: edge
    certificate: <test>
    key: <test>
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
 
